development:
  adapter: postgresql
  encoding: unicode
  database: IGot99Cats_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: IGot99Cats_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: IGot99Cats_production
  pool: 5
